# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NGU4Mjk2MDZmM2E4MjQzZWMxMGM5ZTc5NWEzZjFmYjRlZWNkZDI0ZjVkZGYyMzU2MWM0NmIxM2YzYzQ2OGIxMGJlZTZkN2UyNWU5YTU4ODAxODU2MzUyYTYzY2IwMmVmOTUxNzNhZmYzMTg4Njg2NTRjMzA0M2E5NzBmMzAyYjQ=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: musicPlayer
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password:
