package com.musicplayer.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArtistAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArtistAllPropertiesEquals(Artist expected, Artist actual) {
        assertArtistAutoGeneratedPropertiesEquals(expected, actual);
        assertArtistAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArtistAllUpdatablePropertiesEquals(Artist expected, Artist actual) {
        assertArtistUpdatableFieldsEquals(expected, actual);
        assertArtistUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArtistAutoGeneratedPropertiesEquals(Artist expected, Artist actual) {
        assertThat(actual)
            .as("Verify Artist auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArtistUpdatableFieldsEquals(Artist expected, Artist actual) {
        assertThat(actual)
            .as("Verify Artist relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getBio()).as("check bio").isEqualTo(expected.getBio()))
            .satisfies(a -> assertThat(a.getImage()).as("check image").isEqualTo(expected.getImage()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getVerified()).as("check verified").isEqualTo(expected.getVerified()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArtistUpdatableRelationshipsEquals(Artist expected, Artist actual) {
        assertThat(actual)
            .as("Verify Artist relationships")
            .satisfies(a -> assertThat(a.getSongses()).as("check songses").isEqualTo(expected.getSongses()));
    }
}
