package com.musicplayer.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlaylistAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaylistAllPropertiesEquals(Playlist expected, Playlist actual) {
        assertPlaylistAutoGeneratedPropertiesEquals(expected, actual);
        assertPlaylistAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaylistAllUpdatablePropertiesEquals(Playlist expected, Playlist actual) {
        assertPlaylistUpdatableFieldsEquals(expected, actual);
        assertPlaylistUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaylistAutoGeneratedPropertiesEquals(Playlist expected, Playlist actual) {
        assertThat(actual)
            .as("Verify Playlist auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaylistUpdatableFieldsEquals(Playlist expected, Playlist actual) {
        assertThat(actual)
            .as("Verify Playlist relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()))
            .satisfies(a -> assertThat(a.getCoverImage()).as("check coverImage").isEqualTo(expected.getCoverImage()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaylistUpdatableRelationshipsEquals(Playlist expected, Playlist actual) {
        // empty method
    }
}
