package com.musicplayer.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlayAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayAllPropertiesEquals(Play expected, Play actual) {
        assertPlayAutoGeneratedPropertiesEquals(expected, actual);
        assertPlayAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayAllUpdatablePropertiesEquals(Play expected, Play actual) {
        assertPlayUpdatableFieldsEquals(expected, actual);
        assertPlayUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayAutoGeneratedPropertiesEquals(Play expected, Play actual) {
        assertThat(actual)
            .as("Verify Play auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayUpdatableFieldsEquals(Play expected, Play actual) {
        assertThat(actual)
            .as("Verify Play relevant properties")
            .satisfies(a -> assertThat(a.getPlayedAt()).as("check playedAt").isEqualTo(expected.getPlayedAt()))
            .satisfies(a -> assertThat(a.getDurationListened()).as("check durationListened").isEqualTo(expected.getDurationListened()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlayUpdatableRelationshipsEquals(Play expected, Play actual) {
        assertThat(actual)
            .as("Verify Play relationships")
            .satisfies(a -> assertThat(a.getSong()).as("check song").isEqualTo(expected.getSong()));
    }
}
