package com.musicplayer.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlaylistSongAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaylistSongAllPropertiesEquals(PlaylistSong expected, PlaylistSong actual) {
        assertPlaylistSongAutoGeneratedPropertiesEquals(expected, actual);
        assertPlaylistSongAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaylistSongAllUpdatablePropertiesEquals(PlaylistSong expected, PlaylistSong actual) {
        assertPlaylistSongUpdatableFieldsEquals(expected, actual);
        assertPlaylistSongUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaylistSongAutoGeneratedPropertiesEquals(PlaylistSong expected, PlaylistSong actual) {
        assertThat(actual)
            .as("Verify PlaylistSong auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaylistSongUpdatableFieldsEquals(PlaylistSong expected, PlaylistSong actual) {
        assertThat(actual)
            .as("Verify PlaylistSong relevant properties")
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getAddedAt()).as("check addedAt").isEqualTo(expected.getAddedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlaylistSongUpdatableRelationshipsEquals(PlaylistSong expected, PlaylistSong actual) {
        assertThat(actual)
            .as("Verify PlaylistSong relationships")
            .satisfies(a -> assertThat(a.getPlaylist()).as("check playlist").isEqualTo(expected.getPlaylist()))
            .satisfies(a -> assertThat(a.getSong()).as("check song").isEqualTo(expected.getSong()));
    }
}
