package com.musicplayer.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SongAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSongAllPropertiesEquals(Song expected, Song actual) {
        assertSongAutoGeneratedPropertiesEquals(expected, actual);
        assertSongAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSongAllUpdatablePropertiesEquals(Song expected, Song actual) {
        assertSongUpdatableFieldsEquals(expected, actual);
        assertSongUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSongAutoGeneratedPropertiesEquals(Song expected, Song actual) {
        assertThat(actual)
            .as("Verify Song auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSongUpdatableFieldsEquals(Song expected, Song actual) {
        assertThat(actual)
            .as("Verify Song relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()))
            .satisfies(a -> assertThat(a.getFileUrl()).as("check fileUrl").isEqualTo(expected.getFileUrl()))
            .satisfies(a -> assertThat(a.getCoverImage()).as("check coverImage").isEqualTo(expected.getCoverImage()))
            .satisfies(a -> assertThat(a.getLyrics()).as("check lyrics").isEqualTo(expected.getLyrics()))
            .satisfies(a -> assertThat(a.getReleaseDate()).as("check releaseDate").isEqualTo(expected.getReleaseDate()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSongUpdatableRelationshipsEquals(Song expected, Song actual) {
        assertThat(actual)
            .as("Verify Song relationships")
            .satisfies(a -> assertThat(a.getAlbum()).as("check album").isEqualTo(expected.getAlbum()))
            .satisfies(a -> assertThat(a.getGenre()).as("check genre").isEqualTo(expected.getGenre()))
            .satisfies(a -> assertThat(a.getArtistses()).as("check artistses").isEqualTo(expected.getArtistses()));
    }
}
